[package]
name = "price-feeds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
chainlink = ["dep:futures"]
defillama = ["dep:defillama"]

[dependencies]
defillama = { git = "https://github.com/leruaa/defillama-rs", features = [
    "dashu",
], optional = true }
futures = { version = "0.3", optional = true }
dashu-float = "0.4"
ethers = { version = "2.0", features = ["abigen"] }
async-trait = "0.1"
anyhow = "1.0.72"
thiserror = "1.0.44"
once_cell = "1.18.0"
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
dotenv = "0.15"
